### ISSUE TITLE
Misaligned access at address: 0x3

### ISSUE THREAD

**Issue by LautaroRobles** [littlektframework/littlekt-game-template#7]
I clone the repo, open it with the latest version of Intellij and when I run the `main` function in `com.game.template.LwjglApp.kt` it crashes.

This is the output Intellij's terminal:

```
Executing 'jvmRun -DmainClass=com.game.template.LwjglAppKt --quiet'…

Starting Gradle Daemon...
Gradle Daemon started in 1 s 29 ms
Exception in thread "main" java.lang.IllegalArgumentException: Misaligned access at address: 0x3
	at java.base/java.lang.invoke.VarHandleSegmentViewBase.newIllegalArgumentExceptionForMisalignedAccess(VarHandleSegmentViewBase.java:59)
	at java.base/java.lang.invoke.VarHandleSegmentAsInts.offsetPlain(VarHandleSegmentAsInts.java:99)
	at java.base/java.lang.invoke.VarHandleSegmentAsInts.get(VarHandleSegmentAsInts.java:110)
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.get(AbstractMemorySegmentImpl.java:772)
	at com.littlekt.graphics.webgpu._utilsKt.mapFromIntUntilNull(-utils.kt:57)
	at com.littlekt.graphics.webgpu.Surface.getCapabilities(webgpu.jvm.kt:856)
	at com.littlekt.graphics.webgpu.Surface.getPreferredFormat(webgpu.jvm.kt:867)
	at com.littlekt.LwjglGraphics.preferredFormat_delegate$lambda$0(LwjglGraphics.kt:53)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:83)
	at com.littlekt.LwjglGraphics.getPreferredFormat(LwjglGraphics.kt:53)
	at com.littlekt.resources.internal.InternalResources.load(InternalResources.kt:49)
	at com.littlekt.LwjglContext$start$1.invokeSuspend(LwjglContext.kt:184)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:47)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.littlekt.LwjglContext.start$core(LwjglContext.kt:87)
	at com.littlekt.LittleKtApp.start(LittleKtApp.kt:13)
	at com.game.template.LwjglAppKt.main(LwjglApp.kt:12)
	at com.game.template.LwjglAppKt.main(LwjglApp.kt)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000782ccd8b0d3e, pid=1166325, tid=1166392
#
# JRE version: OpenJDK Runtime Environment Corretto-22.0.2.9.1 (22.0.2+9) (build 22.0.2+9-FR)
# Java VM: OpenJDK 64-Bit Server VM Corretto-22.0.2.9.1 (22.0.2+9-FR, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libEGL_nvidia.so.0+0xb0d3e]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to ./game/core.1166325)
#
# An error report file with more information is saved as:
# ./game/hs_err_pid1166325.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/corretto/corretto-22/issues/
#

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':game:jvmRun'.
> Process 'command '~/.jdks/corretto-22.0.2/bin/java'' finished with non-zero exit value 134

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 11s
Execution finished 'jvmRun -DmainClass=com.game.template.LwjglAppKt --quiet'.
```

This is my gradle config

![Image](https://github.com/user-attachments/assets/94f40c6f-3c55-46ce-ae23-847f27ae47c6)

OS is Pop!_OS 22.04 LTS
CPU is Ryzen 9 7900x
GPU is GTX 970

**Comment by LeHaine** [comment]
This has been fixed in the latest snapshot version of littlekt with the switch to wgpu4k which handles it. You could update your version of littlekt to point to the snapshot to see if that fixes your issue.

**Comment by LautaroRobles** [comment]
I'm sorry but, what snapshot?
The Github Releases only show up to 0.11.0 (which is the version this template is using) https://github.com/littlektframework/littlekt/releases
Maven also only has version 0.11.0 https://mvnrepository.com/artifact/com.littlekt

**Comment by LautaroRobles** [comment]
Ok I'm stupid, I searched everywhere except the [README](https://github.com/littlektframework/littlekt?tab=readme-ov-file#snapshots)

Using the latest commit from master still crashes, but now it's different:

```
Executing 'jvmRun -DmainClass=com.game.template.LwjglAppKt'…

> Task :game:checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :game:compileKotlinJvm UP-TO-DATE
> Task :game:jvmProcessResources NO-SOURCE
> Task :game:jvmMainClasses UP-TO-DATE

> Task :game:jvmRun FAILED
/tmp/wgpu904627442546002981lib
will extract library to path /tmp/wgpu904627442546002981lib
will load library at path /tmp/wgpu904627442546002981lib
2 actionable tasks: 1 executed, 1 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':game:jvmRun'.
> Process 'command '~/.jdks/corretto-22.0.2/bin/java'' finished with non-zero exit value 139

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 626ms
```

This is my config in `libs.versions.toml`

```
[versions]
kotlin = "2.1.0"
kotlinx-html = "0.11.0"
kotlinx-coroutines = "1.9.0"
littlekt = "0.12.0.61ec10a-SNAPSHOT"
```

And `app/build.gradle.kts`

```
repositories {
    maven(url = "https://s01.oss.sonatype.org/content/repositories/snapshots/")
}
```

**Comment by LeHaine** [comment]
Doesn't seem like the exception is displayed in the output, unfortunately. We'd need to dig a bit more to see what the cause is now in order to figure out what we can fix.

Have you run a gradle clean task, by chance? If not, perhaps we could start there.
